"""Flow-map network and its supervised distillation (torch).

G_theta(c, z) -> s, a plain MLP trained by least squares on the labeled
triples generated by the training-free sampler (paper, Section 3.3).
Config-free: hyperparameters come from the example's config module,
passed in as `cfg` (dependency injection, not an import).
"""

import numpy as np
import torch
import torch.nn as nn


class FlowMapNet(nn.Module):
    """G_theta(c, z) -> s, plain MLP (paper, Section 3.3)."""

    def __init__(self, d_c, d_s, hidden, n_layers):
        super().__init__()
        layers = [nn.Linear(d_c + d_s, hidden), nn.Tanh()]
        for _ in range(n_layers - 1):
            layers += [nn.Linear(hidden, hidden), nn.Tanh()]
        layers += [nn.Linear(hidden, d_s)]
        self.net = nn.Sequential(*layers)

    def forward(self, x):
        return self.net(x)


def distill(C, Z, S, device, cfg, seed=None):
    """Supervised regression of the labeled data; returns net + norms.

    cfg must provide HIDDEN, N_LAYERS, LR, N_EPOCHS, BATCH_TRAIN,
    PATIENCE, SEED_TRAIN.
    """
    torch.manual_seed(cfg.SEED_TRAIN if seed is None else seed)
    X = np.hstack([C, Z]).astype(np.float32)
    Y = S.astype(np.float32)
    ok = np.isfinite(X).all(1) & np.isfinite(Y).all(1)
    X, Y = X[ok], Y[ok]
    x_mu, x_sd = X.mean(0), np.maximum(X.std(0), 1e-8)
    y_mu, y_sd = Y.mean(0), np.maximum(Y.std(0), 1e-8)
    Xn = torch.tensor((X - x_mu) / x_sd, device=device)
    Yn = torch.tensor((Y - y_mu) / y_sd, device=device)
    n_val = max(1, int(0.1 * len(Xn)))
    perm = torch.randperm(len(Xn), device=device)
    tr, va = perm[n_val:], perm[:n_val]

    net = FlowMapNet(C.shape[1], S.shape[1],
                     cfg.HIDDEN, cfg.N_LAYERS).to(device)
    opt = torch.optim.Adam(net.parameters(), lr=cfg.LR, weight_decay=1e-6)
    sched = torch.optim.lr_scheduler.ReduceLROnPlateau(opt, factor=0.5,
                                                       patience=20)
    best, best_state, stall = np.inf, None, 0
    for epoch in range(cfg.N_EPOCHS):
        net.train()
        for a in range(0, len(tr), cfg.BATCH_TRAIN):
            b = tr[a:a + cfg.BATCH_TRAIN]
            opt.zero_grad()
            loss = ((net(Xn[b]) - Yn[b]) ** 2).mean()
            loss.backward()
            opt.step()
        net.eval()
        with torch.no_grad():
            val = ((net(Xn[va]) - Yn[va]) ** 2).mean().item()
        sched.step(val)
        if val < best:
            best, stall = val, 0
            best_state = {k: v.detach().clone()
                          for k, v in net.state_dict().items()}
        else:
            stall += 1
        if epoch % 100 == 0:
            print(f"    epoch {epoch:4d}  val {val:.3e}")
        if stall >= cfg.PATIENCE:
            print(f"    early stop at epoch {epoch}  (best {best:.3e})")
            break
    net.load_state_dict(best_state)
    return net, {"x_mu": x_mu, "x_sd": x_sd, "y_mu": y_mu, "y_sd": y_sd,
                 "val_loss": best}
